# Generated by Django 2.2.17 on 2020-11-19 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201119_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='decsription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к изображению'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 19, 22, 34, 11, 635381), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 19, 22, 34, 11, 637381), verbose_name='Дата'),
        ),
    ]
