# Generated by Django 2.2.17 on 2020-12-10 16:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20201119_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 10, 19, 38, 49, 555726), verbose_name='Опубликована')),
                ('image', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к изображению')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
                'db_table': 'catalog',
                'ordering': ['-posted'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 10, 19, 38, 49, 553728), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 10, 19, 38, 49, 554727), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 10, 19, 38, 49, 556726), verbose_name='Дата')),
                ('ready', models.BooleanField(default=False, verbose_name='Состояние')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Catalog', verbose_name='Покупка')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупка',
                'db_table': 'Orders',
                'ordering': ['-date'],
            },
        ),
    ]
