# Generated by Django 2.2.17 on 2020-12-12 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201212_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 12, 20, 30, 14, 42012), verbose_name='Опубликована')),
                ('image', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к изображению')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
                'db_table': 'catalog',
                'ordering': ['-posted'],
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='qnt',
            field=models.IntegerField(default=1, verbose_name='Количество позиций'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 12, 20, 30, 14, 37015), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 12, 20, 30, 14, 39014), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 12, 20, 30, 14, 43012), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product', verbose_name='Покупка'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
