# Generated by Django 2.2.17 on 2021-06-13 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210613_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='on_processing',
            field=models.BooleanField(default=False, verbose_name='В обработке'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 0, 51, 42, 90708), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 0, 51, 42, 92707), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 0, 51, 42, 91707), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 0, 51, 42, 93706), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
