# Generated by Django 2.2.17 on 2021-06-14 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210614_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='stonks',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 23, 41, 21, 415138), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 23, 41, 21, 416137), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 23, 41, 21, 415138), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 23, 41, 21, 417136), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='qnt',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
