# Generated by Django 2.2.17 on 2021-06-14 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210614_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='stonks',
        ),
        migrations.AddField(
            model_name='catalog',
            name='stonks',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 23, 45, 13, 870726), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 23, 45, 13, 872724), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 23, 45, 13, 870726), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 6, 14, 23, 45, 13, 873724), verbose_name='Дата'),
        ),
    ]
