# Generated by Django 2.2.17 on 2021-10-01 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20210615_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 10, 1, 14, 31, 53, 716338), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(max_length=240, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 10, 1, 14, 31, 53, 718337), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='stonks',
            field=models.IntegerField(default=0, verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(max_length=24, unique_for_date='posted', verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 10, 1, 14, 31, 53, 717338), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 10, 1, 14, 31, 53, 719336), verbose_name='Дата'),
        ),
    ]
